name: Protoformer
channels:
    - conda-forge
    - defaults
dependencies:
    - python=3.7
    - pip
    - numpy=1.14.0
    - pandas=0.22
    - matplotlib=2.1.2
    - shap==0.35.0
    - transformers
    - sentence-transformers
    - torch==1.8.1

